---
language: ruby
bundler_args: --without development
script: "bundle exec rake test"
rvm:
- 1.8.7
- 1.9.3
- 2.1.7
- 2.2.3
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 3.8.0" FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 4.2.0"
matrix:
  exclude:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.1.7
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.2.3
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.2.3
    env: PUPPET_VERSION="~> 3.8.0"
  - rvm: 2.2.3
    env: PUPPET_VERSION="~> 3.8.0" FUTURE_PARSER=yes
  - rvm: 1.8.7
    env: PUPPET_VERSION="~> 4.2.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.2.0"
  - rvm: 2.1.7
    env: PUPPET_VERSION="~> 4.2.0"

notifications:
  email: false
